# check the Python filter
# with inline statements without cache
# with code chunks with and without cache
example:
	pandoc example.md --lua-filter filter-python.lua \
		-o example-out.html -s  --css pydoc.css
